apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config-configmap
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.container.config | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasource-configmap
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.container.data | nindent 2 }}
