apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-ds-configmap
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
{{- toYaml .Values.config.data | nindent 2 }}