apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    app.quarkus.io/build-timestamp: 2020-12-03 - 16:42:52 +0000
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: quarkus-kind-mp-showcase
    app.kubernetes.io/version: "0.8"
  name: quarkus-kind-mp-showcase
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-kind-mp-showcase
    app.kubernetes.io/version: "0.8"
  type: ClusterIP
