apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger-asyncapi.fullname" . }}-configmap
  labels:
    {{- include "swagger-asyncapi.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.container.config | nindent 2 }}