apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asyncapi-playground.fullname" . }}-configmap
  labels:
    {{- include "asyncapi-playground.labels" . | nindent 4 }}
data:
  swagger-config.yaml: |
    urls:
      - name: Petstore
        url: "https://petstore.swagger.io/v2/swagger.json"
      - name: Quarkus,
        url: "quarkus-kind-mp-showcase:8080/openapi"