apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
{{- range .Values.config.data }}
  {{ .key }}: {{ .value }}
{{- end}}