kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postgres.fullname" . }}-claim
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi